export const USER_METRICS_CONSTANTS = {
  MIN_WEIGHT: 30,
  MAX_WEIGHT: 300,
  MIN_HEIGHT: 100,
  MAX_HEIGHT: 250,
  MIN_AGE: 10,
  MAX_AGE: 100,
} as const;

export const VALIDATION_CONSTANTS = {
  MIN_CALORIES: 800,
  MAX_CALORIES: 6000,
  MIN_PROTEIN: 20,
  MAX_PROTEIN: 400,
  MIN_CARBS: 20,
  MAX_CARBS: 800,
  MIN_FATS: 10,
  MAX_FATS: 300,
  MIN_DURATION_WEEKS: 1,
  MAX_DURATION_WEEKS: 52,
  MIN_NUTRITION_DAYS: 1,
  MAX_NUTRITION_DAYS: 365,
  MIN_DAYS_PER_WEEK: 1,
  MAX_DAYS_PER_WEEK: 7,
} as const;

